### ISSUE TITLE
[Request] Add ability to contribute destinations via Dagger multibindings

### ISSUE THREAD

**Issue by JohnBuhanan** [roudikk/guia#14]
I'd like to be able to provide navigation generically from feature modules.

The app module could gather all provided navigation via dagger multibindings.

Perhaps something like this:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/16459434/216139236-377562c3-b28a-41bd-ba11-f93a4064d19e.png">

<img width="687" alt="image" src="https://user-images.githubusercontent.com/16459434/216140073-845b7545-5c1d-4412-a05c-2e069f7f0e30.png">

**Comment by roudikk** [comment]
So for the above to work, you require presentations to not be internal? Or perhaps a way to provide the class itself like this in `NavigationConfigBuilder`:

![image](https://user-images.githubusercontent.com/22520376/216268362-184f3a2c-f072-4c66-8e61-cd3b3846f469.png)

That way you can call the above in your app module:

![image](https://user-images.githubusercontent.com/22520376/216268805-da0578fb-d8df-4ee1-95f2-e9d887005be9.png)

Or in case you have to use the `Class<*>`:

![image](https://user-images.githubusercontent.com/22520376/216269399-8fb4c81b-d499-4ec0-8d58-fa7ff3e49e7d.png)

Otherwise, I haven't use Dagger in ages, so is there something more that needs to be added?

**Comment by JohnBuhanan** [comment]
That looks like it would work :)

**Comment by roudikk** [comment]
Alright! I'll add it ^^

**Comment by JohnBuhanan** [comment]
Sweet thank you!  I'll close this :P
